const seats = [
  [
    null,
    null,
    { name: 'A3', selected: false },
    { name: 'A4', selected: false },
    { name: 'A5', selected: false },
    null,
    { name: 'A6', selected: false },
    { name: 'A7', selected: false },
    { name: 'A8', selected: false },
    null,
    null,
  ],
  [
    null,
    { name: 'B2', selected: false },
    { name: 'B3', selected: false },
    { name: 'B4', selected: false },
    { name: 'B5', selected: false },
    null,
    { name: 'B6', selected: false },
    { name: 'B7', selected: false },
    { name: 'B8', selected: false },
    { name: 'B9', selected: false },
    null,
  ],
  [
    { name: 'C1', selected: false },
    { name: 'C2', selected: false },
    { name: 'C3', selected: false },
    { name: 'C4', selected: false },
    { name: 'C5', selected: false },
    null,
    { name: 'C6', selected: false },
    { name: 'C7', selected: false },
    { name: 'C8', selected: false },
    { name: 'C9', selected: false },
    { name: 'C10', selected: false },
  ],
  [
    { name: 'D1', selected: false },
    { name: 'D2', selected: false },
    { name: 'D3', selected: false },
    { name: 'D4', selected: false },
    { name: 'D5', selected: false },
    null,
    { name: 'D6', selected: false },
    { name: 'D7', selected: false },
    { name: 'D8', selected: false },
    { name: 'D9', selected: false },
    { name: 'D10', selected: false },
  ],
];

export default seats;
